language: go
dist: xenial

go:
- "1.9"
- "1.x"
- master

before_install:
  - sudo apt-get install -y rpm build-essential debhelper dh-make fakeroot 

script: 
- go get -v -u ./...
- go test -v ./...

before_deploy:
- chmod +x build_tarballs.sh && ./build_tarballs.sh
- make -C rpm/ 
- dpkg-buildpackage -rfakeroot -uc -us && mv ../*.deb release

deploy:
  provider: releases
  api_key:
    secure: zwQXwHl8WuOAoE1X/AV44QSiZfb5lWSHlZhm8awqR9edheTDXoE/WrHaGfBC8jUOpCzJTXiZ2EFGzB3sAHavX73+r/ECJBuA5iQPFuIt3rA2r9uJA8VpKG5wblio1ryU4kQk3oNbXZCe5VvFvw125B/c6NIfI2INfFqR8jSXjIrxwAeZS4n8aOhw9YcZO0OZMDd6ZguA2QLqvxq+hpqJtWJbmSA8rwSCTTDP+qvHHks0HQeEMuxWNk9GDpDNQ7SwMHFYhNMw9Upy+hOBdawJ6f/S2ERWxCfkYVtqi7SiToVxRc3xb8xC/ZRA5gPHtnriB/vUT99n2eiQkN+fPAFKMxrf2QH6pjdtHKtWtZDQYWIGB6Msl1Wqt/UHbbAHwU56IQ8YQmBAUCq8y2Fq0a/XCYNmwGj33anjRHILoZEs+UrV2DgtgsJRSbAhPXnzn/xK8Yv+8EJBPeui6ZlWyX3YTQVR9wGckQ/xHmcVFxT1v+S6ukqz9GmE39iy6NxhCy1WwRHQrzI/r5tilBCb82EkWmZSNAkq8mgRlfEpE/c+vRuI8ZBMHPOSrQFXtVahmTGVItMhsbfn6IqYcqYUecYQazi3JbDhND4ZWbcWVOMnby2wScPqGlxRhHJP85vffJjIqJnVul3dNoDQXfw1jdys+2RnqjkL/OWXEH3VZuyJNLE 
  file_glob: true
  file: release/**/*
  skip_cleanup: true
  on:
    tags: true
